### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by grinner** [antirez/redis-timeseries#3]
Is there an intended license for this?  I'd like to port it to python.  MIT/BSD would be great, but whatever it is, it is just helpful to know.

**Comment by OriginalPenguin** [comment]
grinner: Did you end up porting this to python?

**Comment by grinner** [comment]
Yes I did but I haven't published it yet due to the lack of a real license, since it's derived from the original ruby.

I will gladly publish it under the MIT License (or other actual license) with permission from the original commiter.  Works great and looks good in python

**Comment by antirez** [comment]
Licensed added, sorry for forgetting about it and about this pull request.

**Comment by grinner** [comment]
Pushed to code

https://github.com/grinner/redis-timeseries-py
